### ISSUE TITLE
Fork the whole Dnscrypt-server-docker server feature wise

### ISSUE THREAD

**Issue by ghost** [junkurihara/encrypted-dns-server-modns#1]
First and foremost: Encrypted-dns-server-modns is great. Thanks for your contibution.

Please fork the whole Dnscrypt-server-docker image including the [local Unbound dns service](https://github.com/jedisct1/dnscrypt-server-docker/blob/master/unbound.sh).

After reading 'Hiding a tree in the wild forest' and using encrypted-dns-server-modns with the default Quad9 DNS service, as Unbound is not present in the encrypted-dns-server-modns docker image.

It seems to me that despite the fact that you are playing hide and seek in the woods. 
Queries can still be logged to the source.

An external DNS service can always log. Whatever they say.
For example Quad9 and Cloudflare's 1.1.1.1.

There is of course a reason that dnscrypt-server-docker uses a local dns service out of the box.
For example like the [Quad9 and Sony case](https://quad9.net/news/blog/quad9-and-sony-music-german-injunction-status/).

Or Cloudflare's DNS service: 1.1.1.1. That falls under the USA jurisprudence [and logs queries](https://www.cloudflare.com/learning/dns/what-is-1.1.1.1/).
Which is of course not desirable.

Of course you can install a local DNS service yourself. Still, it seems easier to me if everything is in an image of Docker out of the box.

Thanks.

**Comment by junkurihara** [comment]
Hi @bertusdebruin 

Thanks for your comment! I understand your concern and I agree to that a docker image combined with unbound is useful.

Actually, each of my experimental resolvers and servers runs with encrypted-dns-server-modns and unbound in single docker container, which is deployed based on the dnscrypt-server-docker repo. So I will make its Dockerfile and docker-compose.yml public on this repo shortly (in a few days). Please wait for a moment!

Best,
Jun

**Comment by ghost** [comment]
@junkurihara 
Thanks!

Don't forget to update the Docker Hub image next to this git repo  :)
Looking forward to it.

**Comment by junkurihara** [comment]
Hi @bertusdebruin 

Here comes the repo!
https://github.com/junkurihara/dnscrypt-server-docker-modns

And its image on docker hub!
https://hub.docker.com/r/jqtype/dnscrypt-server-modns

Enjoy &mu;ODNS 😄 

Jun
